services:
  - type: web
    name: oryzatix-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "ORYZATIX"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array
      - key: RUN_MIGRATIONS
        value: "false"
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gateway01.ap-northeast-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        value: oryzatix
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        value: "*.vercel.app,localhost"
